#!/usr/bin/env bash

set -euo pipefail

if [[ ${1:-} != get ]]; then
    exit 0
fi

declare -A CRED=()
while IFS='=' read -r key value; do
    if [[ -n ${key:-} ]]; then
        CRED[$key]=$value
    else
        break
    fi
done

USERNAME=flrgh

HOST=${CRED[host]:-}
REF=

case $HOST in
    github.com|gist.github.com|api.github.com)
        REF=bws://main/github-helper-token
        ;;
    git.pancakes2.com)
        REF=bws://home/gitea-access-token
        ;;
    *)
        exit 0
        ;;
esac

TOKEN=$(secrets get --cache "$REF")
if [[ -z ${TOKEN:-} ]]; then
    echo "ERROR: failed fetching token for $HOST" >&2
    exit 1
fi

printf 'username=%s\n' "$USERNAME"
printf 'password=%s\n' "$TOKEN"
