#!/usr/bin/env bash

set -euo pipefail

readonly TOKEN_FILE=$HOME/.config/github/helper-access-token

if [[ -e $TOKEN_FILE ]]; then
    source "$TOKEN_FILE"

    printf 'password=%s\n' "$GITHUB_TOKEN"

    if [[ -n ${GITHUB_USER:-} ]]; then
        printf 'username=%s\n' "$GITHUB_USER"
    fi
fi
