#!/usr/bin/env bash

set -euo pipefail

readonly SHARE=${XDG_DATA_HOME:-"$HOME/.local/share"}
readonly MAN=${SHARE}/man
readonly COMPLETIONS=${BASH_COMPLETION_USER_DIR:-"${SHARE}"}/completions


init-dirs() {
    mkdir -p "${MAN}"/man{1,3,5,7}
    mkdir -p "$COMPLETIONS"
}


# 1. creates an `fzf.1` man page from `fzf --man`
post-fzf() {
    local dir="$HOME"/man1
    mkdir -p "$dir"

    local bin; bin=$(mise which fzf)

    # -R tells `man` to re-encode the input rather than formatting it for display
    MANOPT='-R' "$bin" --man > "$MAN/man1/fzf.1"
}


# 1. symlinks github CLI man pages into ~/.local/share/man
post-gh() {
    local -r src=$1

    shopt -s failglob

    for man in "${src}"/*/share/man/man[0-9]; do
        base=${man##*/}
        ln -sfv "${man}"/* "${MAN}/${base}"
    done
}

# 1. symlinks `git-cliff.1` into ~/.local/share/man/man1
# 2. symlinks `git-cliff.bash` bash completion script
post-git-cliff() {
    local -r src=$1

    shopt -s failglob

    ln -sfv "${src}"/*/man/git-cliff.1 "$MAN/man1"

    ln -sfv -T "${src}"/*/completions/git-cliff.bash \
        "$COMPLETIONS/git-cliff"
}


main() {
    local -r name=$1
    local -r fn=post-${name}

    if ! builtin declare -F "$fn" &>/dev/null; then
        return 0
    fi

    init-dirs

    local src; src=$(mise where "$name")

    "$fn" "$src"
}

main "$@"
