# 2024-01-23: these are just defaults from `minijinja-cli --print-config`

format = "auto"
autoescape = "auto"
include = true
newline = true
trim-blocks = false
lstrip-blocks = false
py-compat = false
env = false
strict = false
safe-paths = []
expr-out = "print"
fuel = 0

[syntax]
block-start = "{%"
block-end = "%}"
variable-start = "{{"
variable-end = "}}"
comment-start = "{#"
comment-end = "#}"
line-statement-prefix = ""
line-comment-prefix = ""

[defines]

