#!/usr/bin/env bash

set -euo pipefail

VERSION=${1:-latest}

if [[ $VERSION == latest ]]; then
    VERSION=$(gh-helper get-latest-release-name tree-sitter/tree-sitter)

    echo "Detected latest version $VERSION"
fi


SRC=$(cache-get \
    "https://github.com/tree-sitter/tree-sitter/releases/download/${VERSION}/tree-sitter-linux-x64.gz" \
    "tree-sitter-${VERSION}.gz"
)

cd "$(mktemp -d)"

gunzip -d < "$SRC" > "$HOME/.local/bin/tree-sitter"
chmod +x "$HOME/.local/bin/tree-sitter"

tree-sitter --version
