#!/usr/bin/env bash

set -euo pipefail

readonly REPO=junegunn/fzf

VERSION=${1:-latest}

if [[ $VERSION == latest ]]; then
    VERSION=$(gh-helper get-latest-release-name "$REPO")
    echo "Detected latest version $VERSION"
fi


SRC=$(cache-get \
    https://github.com/junegunn/fzf/releases/download/${VERSION}/fzf-${VERSION}-linux_amd64.tar.gz \
    "fzf-${VERSION}.tar.gz"
)

cd "$(mktemp -d)"
tar xzf "$SRC"
mv fzf "$HOME/.local/bin/"

fzf --version
