#!/usr/bin/env bash

# installs the 1password CLI (GUI is already packaged)
#
# Links:
#  * https://support.1password.com/command-line-getting-started/
#  * https://app-updates.agilebits.com/product_history/CLI

set -euo pipefail

VERSION=${1:-latest}

readonly GPG_KEY=3FEF9748469ADBE15DA7CA80AC2D62742012EA22
readonly LIST_URL=https://app-updates.agilebits.com/product_history/CLI

if [[ $VERSION == latest ]]; then
    # oof...
    VERSION=$(
        curl -s "$LIST_URL" \
        | sed -n -r -e 's|.*/pkg/v([0-9.]+)/op_linux_amd64.*|\1|p' \
        | sort -r --version-sort \
        | head -1
    )

    if [[ -z $VERSION ]]; then
        echo "failed getting latest version from $LIST_URL"
    fi
fi

readonly URL="https://cache.agilebits.com/dist/1P/op/pkg/v${VERSION}/op_linux_amd64_v${VERSION}.zip"


if command -v op &>/dev/null; then
    installed=$(op --version)
    if [[ $installed = $VERSION ]]; then
        echo "op $VERSION is already installed :)"
        exit 0
    fi
fi

echo "installing 1password cli version $VERSION"

gpg2 --receive-keys "$GPG_KEY"

tmp=$(mktemp -d)
cd "$tmp" || { echo "failed to cd to temp dir ($tmp), exiting"; exit 1; }

cleanup() {
    rm -r "$tmp"
}

trap cleanup ERR EXIT

FNAME=$(cache-get "$URL" "op-${VERSION}.zip")

unzip "$FNAME"

gpg2 --verify op.sig op

mv -v op "$HOME/.local/bin/"

op --version
