#!/usr/bin/env bash

set -euo pipefail

if ! command -v npm &>/dev/null; then
    install-node
fi

npm install -g \
    bash-language-server \
    pyright \
    sql-language-server \
    vscode-json-languageserver \
    yaml-language-server \
    awk-language-server \
    dockerfile-language-server-nodejs
