#!/usr/bin/env bash

VERSION=${1:-latest}

if [[ $VERSION == latest ]]; then
    VERSION=$(gh-helper get-latest-tag sumneko/lua-language-server)
    echo "Latest version is $VERSION"
fi

docker build \
    --build-arg TAG="$VERSION" \
    --build-arg J=$(nproc) \
    -t "lsp/lua:$VERSION" \
    -t "lsp/lua:latest" \
    - \
<< 'EOF'
FROM alpine:latest

ARG TAG=master
ARG J=1

WORKDIR /opt

RUN apk add \
        libgcc \
        libstdc++ && \
    apk add --virtual deps \
        bash \
        ninja \
        g++ \
        git \
        gcc \
        && \
    git clone \
        --branch "$TAG" \
        --depth 1 \
        --recurse-submodules \
        --shallow-submodules \
        --jobs "$J" \
        https://github.com/sumneko/lua-language-server && \
    cd /opt/lua-language-server/3rd/luamake && \
    ./compile/install.sh && \
    cd /opt/lua-language-server && \
    ./3rd/luamake/luamake rebuild && \
    apk del deps && \
    rm -rf \
        /opt/lua-language-server/3rd/luamake \
        /opt/lua-language-server/.git \
        /opt/lua-language-server/locale/zh-cn

WORKDIR /opt/lua-language-server

ENTRYPOINT ["/opt/lua-language-server/bin/lua-language-server", "/opt/lua-language-server/main.lua"]
EOF
