#!/usr/bin/env bash

VERSION=${1:-latest}

if [[ $VERSION == latest ]]; then
    VERSION=$(gh-helper get-latest-tag sumneko/lua-language-server)
    echo "Latest version is $VERSION"
fi

URL=https://github.com/sumneko/lua-language-server/releases/download/${VERSION}/lua-language-server-${VERSION}-linux-x64.tar.gz

F=$(cache-get "$URL" lua-language-server-${VERSION}.tar.gz)

TEMP=$(mktemp -d)

tar -C "$TEMP" -xzf "$F"

rsync -HavP \
    --remove-source-files \
    --delete \
    "$TEMP/" \
    "$HOME/.local/libexec/lua-language-server/"

lua-language-server --version
