[global]

strict_env = true

[whitelist]
exact = [
    "/home/michaelm/.envrc"
]

prefix = [
    "/home/michaelm/pagely-git",
    "/home/michaelm/git/att",
    "/home/michaelm/git/kong",
    "/home/michaelm/git/flrgh",
]
