#!/usr/bin/env bash

set -euo pipefail

VERSION=$(gh-helper get-latest-release-name bazelbuild/bazel)

URL=https://github.com/bazelbuild/bazel/releases/download/${VERSION}/bazel-${VERSION}-installer-linux-x86_64.sh

ASSET=$(cache-get "$URL")
if [[ -z ${ASSET:-} ]]; then
    echo "FATAL: failed downloading"
    exit 1
fi

unzip -q -p "$ASSET" bazel-complete.bash
