#!/usr/bin/env bash

export MISE_INSTALL_PATH=$HOME/.local/bin/mise
if [[ -x $MISE_INSTALL_PATH ]]; then
    echo "mise is already installed at $MISE_INSTALL_PATH"
    exit 0
fi

if [[ -z ${GITHUB_TOKEN:-} ]]; then
    if [[ -e $HOME/.config/github/helper-access-token ]]; then
        source "$HOME/.config/github/helper-access-token"
    fi
fi
if [[ -n ${GITHUB_TOKEN:-} ]]; then
    export GITHUB_API_TOKEN=${GITHUB_TOKEN}
fi

export MISE_INSTALL_HELP=1
export MISE_DEBUG=1
export MISE_QUIET=0
curl https://mise.run | sh
