#!/usr/bin/env bash

export MISE_INSTALL_PATH=$HOME/.local/bin/mise
if [[ -x $MISE_INSTALL_PATH ]]; then
    echo "mise is already installed at $MISE_INSTALL_PATH"
    exit 0
fi

source ./home/.local/lib/bash/github-helper-token.bash

export MISE_INSTALL_HELP=1
export MISE_DEBUG=1
export MISE_QUIET=0
curl https://mise.run | sh
