#!/usr/bin/env bash

set -euo pipefail

source ./home/.local/lib/bash/github-helper-token.bash

export CARGO_HOME=${CARGO_HOME:-$HOME/.local/cargo}
export RUSTUP_HOME=${RUSTUP_HOME:-$HOME/.local/rustup}

if ! command -v cargo-binstall &>/dev/null; then
    echo "error: cargo-binstall not found"
    exit 1
fi

if (( $# == 0 )); then
    echo "usage: install-cargo-packages PACKAGE..." >&2
    exit 1
fi

cargo binstall \
    --no-confirm \
    --continue-on-failure \
    "$@"
