#!/usr/bin/env bash

set -euo pipefail

source ./home/.local/lib/bash/github-helper-token.bash

export CARGO_HOME=${CARGO_HOME:-$HOME/.local/cargo}
export RUSTUP_HOME=${RUSTUP_HOME:-$HOME/.local/rustup}

if ! command -v cargo-binstall &>/dev/null; then
    echo "error: cargo-binstall not found"
    exit 1
fi

declare -a PACKAGES=()
mapfile -t PACKAGES < <(./scripts/get-lines ./deps/cargo-packages.txt)

cargo binstall \
    --no-confirm \
    --continue-on-failure \
    "${PACKAGES[@]}"
