#!/usr/bin/env bash

# removes any files which are present in ~/.local/share/mise/shims

set -euo pipefail

readonly BINS=(
    "$HOME/.local/bin"
    "$HOME/.local/cargo/bin"
    "$HOME/.local/go/bin"
)
readonly VBIN=$HOME/.local/vbin

readonly SHIMS=${XDG_DATA_HOME:-${HOME}/.local/share}/mise/shims

shopt -s nullglob

mise reshim --force

FILES=( "${SHIMS}"/* )

rm -rfv "${FILES[@]/#"$SHIMS"/"${VBIN}"}"

for dir in "${BINS[@]}"; do
    rm -fv "${FILES[@]/#"$SHIMS"/"${dir}"}"
done
