#!/usr/bin/env bash

# mise has a minimum_release_age setting, but this only applies to the tools that
# it manages and not mise itself
#
# mise uses cal-ver, _but_ release publish date usually doesn't match the cal-ver
# date (e.g. version `2026.6.12` was published 2026-06-22)

set -euo pipefail

readonly REPO=jdx/mise
readonly MIN_DAYS=7
readonly MIN_AGE=$(( EPOCHSECONDS - (MIN_DAYS * 60 * 60 * 24) ))

main() {
    local version
    version=$(
        gh-helper get-stable-releases "$REPO" \
        | jq -r \
            --argjson MIN_AGE "$MIN_AGE" \
        '
            map(
                {
                    published_at,
                    created_at,
                    age: ([.published_at, .created_at] | max),
                    tag: (.tag_name | ltrimstr("v")),
                    assets: (.assets | length ),
                }

                # filter anything without assets
                | select(.assets > 0)

                # filter anything newer than MIN_AGE
                | select((.age | fromdateiso8601) <= $MIN_AGE)
            )

            | max_by(.created_at)
            | .tag
        '
    )

    if [[ -z $version || $version == null ]]; then
        echo "no stable $REPO release at least ${MIN_AGE}d old was found" >&2
        return 1
    fi


    local current
    current=$(mise version --quiet | sed -nre 's/^([0-9]{4}\.[0-9]{1,2}\.[0-9]{1,2}).*/\1/p')

    if [[ $current == "$version" || $current > "$version" ]]; then
        echo "mise is already up to date at $current"
        return
    fi

    echo "Updating mise to $version (newest release >= ${MIN_DAYS}d old)"

    mise self-update --yes "$version"
}

main "$@"
