#!/usr/bin/env bash

set -euo pipefail

readonly NVIM=${XDG_DATA_HOME:?}/nvim
readonly BUNDLE=$NVIM/_bundle

rm -rf "$BUNDLE" || true
mkdir -p "$BUNDLE"

shopt -s nullglob

TYPES=(
    "autoload" # automatically loaded scripts
    "colors"   # color scheme files
    "compiler" # compiler files
    "doc"      # documentation
    "ftplugin" # filetype plugins
    "indent"   # indent scripts
    "keymap"   # key mapping files
    "lang"     # menu translations
    "lsp"      # LSP client configurations
    "lua"      # Lua
    "pack"     # packages
    "parser"   # treesitter syntax parsers
    "plugin"   # plugin scripts
    "queries"  # treesitter queries
    "rplugin"  # remote-plugin scripts
    "spell"    # spell checking files
    "syntax"   # syntax files
    "tutor"    # tutorial files
)

for t in "${TYPES[@]}"; do
    mkdir -p "$BUNDLE/$t" "$BUNDLE/after/$t"

    echo "$t"
    for src in "$NVIM"/lazy/*/"$t"; do
        cp \
            --no-clobber \
            --verbose \
            --recursive \
            --link \
            --target-directory "$BUNDLE/$t" \
            "$src"/*
    done

    echo "after/$t"
    for src in "$NVIM"/lazy/*/after/"$t"; do
        cp \
            --no-clobber \
            --verbose \
            --recursive \
            --link \
            --target-directory "$BUNDLE/after/$t" \
            "$src"/*
    done
done


rm -f "$BUNDLE/doc/tags"
touch "$BUNDLE/doc/tags"
for tag in "$NVIM"/lazy/*/doc/tags; do
    cat "$tag" >> "$BUNDLE/doc/tags"
done

find "$BUNDLE" \
    -type d \
    -empty \
    -delete
