[global]

# `set -euo pipefail` when evaluating .envrc
strict_env = true

# don't read from /dev/stdin when evaluating .envrc
disable_stdin = true

[whitelist]
exact = [
    "/home/michaelm/.envrc"
]

prefix = [
    "/home/michaelm/pagely-git",
    "/home/michaelm/git/att",
    "/home/michaelm/git/kong",
    "/home/michaelm/git/flrgh",
]
