import = ["/home/michaelm/.config/alacritty/alacritty.local.yml", "/home/michaelm/.config/alacritty/catppuccin-mocha.toml"]
ipc_socket = false
live_config_reload = true
working_directory = "None"

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
ALACRITTY = "1"
TERM = "alacritty"

[font.normal]
family = "LiterationMono Nerd Font"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
action = "Select"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Select"
post_processing = true
regex = "[0-9a-f]{40}"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Select"
post_processing = true
regex = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Control|Shift"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
decorations_theme_variant = "None"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 90
lines = 60

[window.padding]
x = 0
y = 0
