#!/usr/bin/env bash

set -euo pipefail

readonly REPO=bitwarden/cli
readonly BASE_URL=https://github.com/bitwarden/cli/releases/download

VERSION=${1:-latest}

if [[ $VERSION == latest ]]; then
    VERSION=$(gh-helper get-latest-tag "$REPO")
fi

VERSION=${VERSION#*v}

echo "Installing bitwarden cli version $VERSION"

ZIP=$(cache-get "${BASE_URL}/v${VERSION}/bw-linux-${VERSION}.zip")
SUM=$(cache-get "${BASE_URL}/v${VERSION}/bw-linux-sha256-${VERSION}.txt")

echo "Validating download checksum"

CHECKSUM=$(tr -d $'\r' < "$SUM")
printf "%q %q\n" "$CHECKSUM" "$ZIP" \
| sha256sum --check --strict

TMP=$(mktemp)

unzip -v -p "$ZIP" > "$TMP"
chmod +x "$TMP"
mv -v "$TMP" "$HOME/.local/bin/bw"

bw --version
